#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
---
#@ if ((data.values.tap.credentials.registry.host).find(".dkr.ecr.") > -1) == False:
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: container-registry-credentials
  namespace: #@ data.values.tas_adapter.namespace
spec:
  fromNamespace: #@ data.values.tap.namespace
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: container-registry-credentials
  namespace: #@ data.values.tas_adapter.namespace
spec:
  toNamespace: cf
#@ end
