#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tas-adapter-default-sa
  namespace: #@ data.values.tas_adapter.namespace
  annotations:
    kapp.k14s.io/change-group: tas-adapter-install/rbac
    kapp.k14s.io/change-rule: "delete after deleting tas-adapter-install/tas-adapter"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tas-adapter-default-role
  annotations:
    kapp.k14s.io/change-group: tas-adapter-install/rbac
    kapp.k14s.io/change-rule: "delete after deleting tas-adapter-install/tas-adapter"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tas-adapter-default-role-binding
  annotations:
    kapp.k14s.io/change-group: tas-adapter-install/rbac
    kapp.k14s.io/change-rule: "delete after deleting tas-adapter-install/tas-adapter"
subjects:
- kind: ServiceAccount
  name: tas-adapter-default-sa
  namespace: #@ data.values.tas_adapter.namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tas-adapter-default-role
