name: "Tanzu Kubernetes Grid Create Management Cluster Github Action"
description: "Creates a management cluster and vends the Base64-encoded contents of the .kube-tkg/config file"
inputs:
  path-to-cluster-config:
    description: "Path to management cluster configuration"
    required: true
  bootstrap-kubeconfig-contents:
    description: "The base64 encoded contents of a .kube/config file for a Kind cluster that has the current Kubernetes cluster context set"
    required: true
  management-kubeconfig-contents:
    description: "The base64 encoded contents of a .kube/config file from a TKG management cluster that already has the current Kubernetes cluster context set. (If supplied, we'll attempt to authenticate, if successful we will skip management cluster creation and just set the output of this action to be the same)."
    required: false
  csp-api-token:
    description: "VMware Cloud Service Platform API Token, used for authenticating to the VMware Marketplace"
    required: true
  azure-ad-client-id:
    description: "An Azure Active Directory application identifier"
    required: true
  azure-ad-client-secret:
    description: "A secret associated with an Azure Active Directory application identifier"
    required: true
  azure-subscription-id:
    description: "A GUID that uniquely identifies your subscription to use Azure services"
    required: true
  azure-tenant-id:
    description: "A GUID for your Azure tenant"
    required: true
  azure-region:
    description: "An Azure region"
    required: false
outputs:
  create_secret:
    description: "Whether or not to create a Github secret. (Never overwrite an existing secret)."
  kubeconfig_contents:
    description: "The base64 encoded contents of a .kube/config file from a TKG management cluster that already has the current Kubernetes cluster context set"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.path-to-cluster-config }}"
    - "${{ inputs.bootstrap-kubeconfig-contents }}"
    - "${{ inputs.management-kubeconfig-contents }}"
  env:
    TANZU_CLI_VERSION: 2.3.0
    TANZU_CLI_CORE_VERSION: 0.90.1
    CSP_API_TOKEN: ${{ inputs.csp-api-token }}
    AZURE_SUBSCRIPTION_ID: ${{ inputs.azure-subscription-id }}
    AZURE_AD_TENANT_ID: ${{ inputs.azure-tenant-id }}
    AZURE_AD_CLIENT_ID: ${{ inputs.azure-ad-client-id }}
    AZURE_AD_CLIENT_SECRET: ${{ inputs.azure-ad-client-secret }}
    AZURE_REGION: ${{ inputs.azure-region }}
