apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-sa
  namespace: tanzu-user-managed-packages
  annotations:
    kapp.k14s.io/change-group: "tanzu-ingress/rbac"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-cluster-role
  annotations:
    kapp.k14s.io/change-group: "tanzu-ingress/rbac"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-cluster-role-binding
  annotations:
    kapp.k14s.io/change-group: "tanzu-ingress/rbac"
subjects:
- kind: ServiceAccount
  name: ingress-sa
  namespace: tanzu-user-managed-packages
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-cluster-role