#@data/values

#@overlay/match-child-defaults missing_ok=True
---
aws:
  credentials:
    accessKey: XXX
    secretKey: YYY
  region: us-east-1
  route53:
    hosted_zone_id: AAAAAAAAA

acme:
  email: tonystark@ironman.me
