apiVersion: v1
kind: ServiceAccount
metadata:
  name: lcs-sa
  namespace: learningcenter-supplemental
  annotations:
    kapp.k14s.io/change-group: "learningcenter-supplemental/rbac"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lcs-cluster-role
  annotations:
    kapp.k14s.io/change-group: "learningcenter-supplemental/rbac"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lcs-cluster-role-binding
  annotations:
    kapp.k14s.io/change-group: "learningcenter-supplemental/rbac"
subjects:
- kind: ServiceAccount
  name: lcs-sa
  namespace: learningcenter-supplemental
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lcs-cluster-role