apiVersion: v1
kind: ServiceAccount
metadata:
  name: tanzu-data-services-sa
  namespace: tanzu-package-repo-data-services
  annotations:
    kapp.k14s.io/change-group: tanzu-data-services/rbac
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tanzu-data-services-cluster-role
  annotations:
    kapp.k14s.io/change-group: tanzu-data-services/rbac
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tanzu-data-services-cluster-admin-cluster-role-binding
  annotations:
    kapp.k14s.io/change-group: tanzu-data-services/rbac
subjects:
- kind: ServiceAccount
  name: tanzu-data-services-sa
  namespace: default
- kind: ServiceAccount
  name: tanzu-data-services-sa
  namespace: tanzu-package-repo-data-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-data-services-cluster-role
