#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")
---
#@ def tn_config():
#@  return {
#@    "auths": {
#@      data.values.tanzuNet.host: {
#@        "username": data.values.tanzuNet.username,
#@        "password": data.values.tanzuNet.password
#@      }
#@    }
#@  }
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-network-credentials
  namespace: #@ data.values.scg.namespace
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting scg-operator"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: #@ json.encode(tn_config())

