#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

---
#@ def config():
profile: run

excluded_packages:
  - cert-manager.tanzu.vmware.com
  - contour.tanzu.vmware.com
  - policy.apps.tanzu.vmware.com

#! installed_for_vmware_internal_use: "true"
ceip_policy_disclosed: true

shared:
  ingress_domain: #@ data.values.tap.domains.main
  ingress_issuer: #@ data.values.tap.cluster.issuerRef.name

#! supply_chain can be configured to be either [ basic, testing_scanning ]
supply_chain: testing_scanning

ootb_supply_chain_basic:
  cluster_builder: #@ data.values.tap.supply_chain.cluster_builder
  registry:
    server: #@ data.values.tap.credentials.registry.host
    repository: #@ data.values.tap.registry.repositories.ootbSupplyChain
  #@ if data.values.tap.supply_chain.gitops.enabled == "true":
  external_delivery: true
  gitops:
    ssh_secret: #@ data.values.tap.supply_chain.gitops.ssh_secret
    repository_owner: #@ data.values.tap.supply_chain.gitops.repository.owner
    repository_name: #@ data.values.tap.supply_chain.gitops.repository.name
    server_address: #@ "https://{}/".format(data.values.tap.supply_chain.gitops.provider)
    branch:  #@ data.values.tap.supply_chain.gitops.repository.branch
    commit_strategy: pull_request
    pull_request:
      server_kind: github
      commit_branch: ""
      pull_request_body: "Generated by TAP Basic Supply Chain"
  #@ end
  git_implementation: #@ data.values.tap.supply_chain.git_implementation

ootb_supply_chain_testing_scanning:
  cluster_builder: #@ data.values.tap.supply_chain.cluster_builder
  registry:
    server: #@ data.values.tap.credentials.registry.host
    repository: #@ data.values.tap.registry.repositories.ootbSupplyChain
  #@ if data.values.tap.supply_chain.gitops.enabled == "true":
  external_delivery: true
  gitops:
    ssh_secret: #@ data.values.tap.supply_chain.gitops.ssh_secret
    repository_owner: #@ data.values.tap.supply_chain.gitops.repository.owner
    repository_name: #@ data.values.tap.supply_chain.gitops.repository.name
    server_address: #@ "https://{}/".format(data.values.tap.supply_chain.gitops.provider)
    branch:  #@ data.values.tap.supply_chain.gitops.repository.branch
    commit_strategy: pull_request
    pull_request:
      server_kind: github
      commit_branch: ""
      pull_request_body: "Generated by TAP Testing and Scanning Supply Chain"
  #@ end

contour:
  envoy:
    service:
      type: LoadBalancer

cnrs:
  default_tls_secret: #@ "{}/{}".format(data.values.tap.ingress.contour_tls_namespace, data.values.tap.ingress.contour_tls_secret)
  domain_name: #@ data.values.tap.domains.knative
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
  ingress:
    internal:
      namespace: tanzu-system-ingress
    external:
      namespace: tanzu-system-ingress

appliveview_connector:
  backend:
    sslDisabled: false
    ingressEnabled: true
    host: #@ "appliveview.{}".format(data.values.tap.domains.main)

package_overlays:
- name: ootb-templates
  secrets:
  - name: honor-deliverable-subpath-overlay

image_policy_webhook:
  allow_unmatched_images: true

#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: #@ data.values.tap.namespace
type: Opaque
stringData:
  values.yml: #@ yaml.encode(config())

