name: "Tanzu CLI Setup Action"
description: "Execute a command with the gcloud, kubectl or tanzu CLI"
inputs:
  enable-tanzu-cli:
    description: "Whether or not to install the tanzu CLI and configure plugins"
    required: false
    default: "false"
  command:
    description: "The kubectl or tanzu CLI command to execute"
    required: true
    default: "tanzu version"
  query-for-output:
    description: "What may be applied to fetch result of command execution.  (Must be an quoted string-value)."
    required: false
  kubeconfig-contents:
    description: "The base64 encoded contents of a .kube/config file that already has the current Kubernetes cluster context set"
    required: false
  csp-api-token:
    description: "VMware Cloud Service Platform API Token, used for authenticating to the VMware Marketplace"
    required: true
  google-project-id:
    description: "The Google project identifier"
    required: true
  google-service-account-key:
    description: "The base64 encoded content of the service account JSON file"
    required: true
outputs:
  result:
    description: "The result of evaluating query-for-output"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.command }}"
    - "${{ inputs.kubeconfig-contents }}"
    - "${{ inputs.query-for-output }}"
  env:
    TANZU_CLI_VERSION: 2.2.0
    TANZU_CLI_CORE_VERSION: 0.29.0
    CSP_API_TOKEN: ${{ inputs.csp-api-token }}
    GOOGLE_PROJECT_ID: ${{ inputs.google-project-id }}
    GOOGLE_SERVICE_ACCOUNT_KEY: ${{ inputs.google-service-account-key }}
    TANZU_CLI_ENABLED: ${{ inputs.enable-tanzu-cli }}
