name: "Tanzu Run Shell Script Setup Action"
description: "Execute a shell script where kubectl and/or tanzu CLI commands may be invoked one or more times"
inputs:
  enable-tanzu-cli:
    description: "Whether or not to install the tanzu CLI and configure plugins"
    required: false
    default: "false"
  script-contents:
    description: "The base64 encoded contents of a shell script"
    required: true
  script-arguments:
    description: "A space separated set of arguments that the script will consume"
    required: true
  kubeconfig-contents:
    description: "The base64 encoded contents of a .kube/config file that already has the current Kubernetes cluster context set"
    required: false
  csp-api-token:
    description: "VMware Cloud Service Platform API Token, used for authenticating to the VMware Marketplace"
    required: true
  azure-ad-client-id:
    description: "An Azure Active Directory application identifier"
    required: true
  azure-ad-client-secret:
    description: "A secret associated with an Azure Active Directory application identifier"
    required: true
  azure-subscription-id:
    description: "A GUID that uniquely identifies your subscription to use Azure services"
    required: true
  azure-tenant-id:
    description: "A GUID for your Azure tenant"
    required: true
  azure-region:
    description: "An Azure region"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.script-contents }}"
    - "${{ inputs.script-arguments }}"
    - "${{ inputs.kubeconfig-contents }}"
  env:
    TANZU_CLI_VERSION: 2.1.0
    TANZU_CLI_CORE_VERSION: 0.28.0
    CSP_API_TOKEN: ${{ inputs.csp-api-token }}
    AZURE_SUBSCRIPTION_ID: ${{ inputs.azure-subscription-id }}
    AZURE_AD_TENANT_ID: ${{ inputs.azure-tenant-id }}
    AZURE_AD_CLIENT_ID: ${{ inputs.azure-ad-client-id }}
    AZURE_AD_CLIENT_SECRET: ${{ inputs.azure-ad-client-secret }}
    AZURE_REGION: ${{ inputs.azure-region }}
    TANZU_CLI_ENABLED: ${{ inputs.enable-tanzu-cli }}
