#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
#@ if (data.values.tap.cluster.provider == "eks" or data.values.tap.cluster.provider == "tkg»aws") and (data.values.tap.credentials.registry.host).find(".dkr.ecr.") > -1:
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xworkloadecrrepos.tap.vrabbi.cloud
spec:
  group: tap.vrabbi.cloud
  names:
    kind: XWorkloadECRRepo
    plural: xworkloadecrrepos
  claimNames:
    kind: WorkloadECRRepo
    plural: workloadecrrepos
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  workloadName:
                    type: string
                  repoPrefix:
                    type: string
                  region:
                    type: string
                  providerName:
                    type: string
                required:
                - region
                - repoPrefix
                - workloadName
                - providerName
            required:
            - parameters
#@ end