name: "aws-08-administer-elastic-container-registry"

on:
  workflow_call:
    inputs:
      repository-names:
        description: "Comma-separated list of names of ECR registry repositories; these can only be alphanumeric"
        required: true
        type: string
      region:
        description: "The AWS region where the Elastic Container Registry will be available"
        type: string
        required: true
      action:
        required: true
        type: string
        description: "Create (new) or destroy (existing)"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: false
      TF_BACKEND_S3_BUCKET_NAME:
        required: true
      AWS_KMS_ALIAS:
        required: true
    outputs:
      ecr_admin_username:
        description: "The username associated with the Elastic Container Registry admin account"
        value: ${{ jobs.terraform.outputs.ecr_admin_username }}
      ecr_admin_password:
        description: "The password associated with the Elastic Container Registry admin account"
        value: ${{ jobs.terraform.outputs.ecr_admin_password }}
      ecr_endpoint:
        description: "The URL that can be used to log into the container image registry (typically {aws_account_id}.dkr.ecr.{region}.amazonaws.com)"
        value: ${{ jobs.terraform.outputs.ecr_endpoint }}

jobs:
  terraform:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ inputs.region }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_repository_names: ${{ inputs.repository-names }}
    runs-on: ubuntu-22.04

    outputs:
      ecr_endpoint: ${{ steps.set_outputs.outputs.ecr_endpoint }}
      ecr_admin_username: ${{ steps.set_outputs.outputs.ecr_admin_username }}
      ecr_admin_password: ${{ steps.set_outputs.outputs.ecr_admin_password }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-22.04, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform/aws/registry

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
        terraform_version: 1.5.6

    - name: Generate backend configuration
      run: |
          cp ../backend/backend.tf .
          echo "bucket = \"${{ secrets.TF_BACKEND_S3_BUCKET_NAME }}\"" > config.aws.tfbackend
          echo "key = \"registry/terraform.tfstate\"" >> config.aws.tfbackend
          echo "region = \"${{ env.AWS_REGION }}\"" >> config.aws.tfbackend
          echo "encrypt = true" >> config.aws.tfbackend
          echo "kms_key_id = \"${{ secrets.AWS_KMS_ALIAS }}\"" >> config.aws.tfbackend
          echo "dynamodb_table = \"${{ secrets.TF_BACKEND_S3_BUCKET_NAME }}\"" >> config.aws.tfbackend

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -upgrade -backend-config=./config.aws.tfbackend

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      if: inputs.action == 'create'
      run: terraform plan

    - name: Terraform Apply
      if: inputs.action == 'create'
      run: terraform apply -auto-approve

    - name: Terraform Destroy
      if: inputs.action == 'destroy'
      run: terraform destroy -auto-approve

    - name: Set Outputs
      id: set_outputs
      if: inputs.action == 'create'
      run: |
        ecr_endpoint=$(terraform output --raw ecr_endpoint | sed 's/https\?:\/\///')
        echo "ecr_endpoint=${ecr_endpoint}" >> $GITHUB_OUTPUT
        ecr_admin_username=$(terraform output --raw ecr_admin_username)
        echo "ecr_admin_username=${ecr_admin_username}" >> $GITHUB_OUTPUT
        ecr_admin_password=$(terraform output --raw ecr_admin_password)
        echo "ecr_admin_password=${ecr_admin_password}" >> $GITHUB_OUTPUT