name: "aws-02-dispatch-remote-backend-for-terraform-state"

on:
  workflow_dispatch:
    inputs:
      aws-access-key-id:
        description: "AWS access key identifier for an account with write permissions to manage S3 buckets and DynamoDB tables"
        required: true
      aws-secret-access-key:
        description: "AWS secret access key for an account with write permissions to manage S3 buckets and DynamoDB tables"
        required: true
      aws-session-token:
        description: "An expiring token used by AWS to validate the temporary security credentials issued."
        required: false
      s3-bucket-name:
        description: "S3 storage bucket name used for Terraform state. (This value will be suffixed. On destroy, be sure to use suffixed name)."
        required: true
        type: string
        default: "tap"
      region:
        description: "The AWS region where the S3 bucket will be created to manage Terraform state"
        required: true
        type: choice
        options:
        - us-east-1
        - us-east-2
        - us-west-2
        - af-south-1
        - ap-east-1
        - ap-south-1
        - ap-northeast-1
        - ap-northeast-2
        - ap-northeast-3
        - ap-southeast-1
        - ap-southeast-2
        - ca-central-1
        - eu-west-1
        - eu-west-2
        - eu-west-3
        - eu-north-1
        - eu-south-1
        - me-south-1
        - sa-east-1
        default: "us-west-2"
      action:
        required: true
        type: choice
        description: "Create (new) or destroy (existing)"
        options:
        - create
        - destroy

jobs:
  manage-backend-storage:
    uses: ./.github/workflows/aws-provided-remote-backend.yml
    with:
      s3-bucket-name: ${{ github.event.inputs.s3-bucket-name }}
      region: ${{ github.event.inputs.region }}
      action: ${{ github.event.inputs.action }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ github.event.inputs.aws-access-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.aws-secret-access-key }}
      AWS_SESSION_TOKEN: ${{ github.event.inputs.aws-session-token }}
      PA_TOKEN: ${{ secrets.PA_TOKEN }}
      AWS_KMS_ALIAS: ${{ secrets.AWS_KMS_ALIAS }}
