name: "aws-obtain-base64-encoded-kubeconfig-for-cluster"

on:
  workflow_call:
    inputs:
      cluster-name:
        description: "Name of an existing EKS cluster"
        required: true
        type: string
      region:
        description: "The AWS region where region where the cluster is deployed"
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: false
    outputs:
      b64kubeconfig:
        description: "Base64 encoded contents of .kube/config for named cluster"
        value: ${{ jobs.aws-cli.outputs.b64kubeconfig }}

jobs:
  aws-cli:
    runs-on: ubuntu-22.04
    env:
      AWS_PAGER: ""

    outputs:
      b64kubeconfig: ${{ steps.encode_kubeconfig.outputs.b64kubeconfig }}

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ inputs.region }}
        mask-aws-account-id: false

    - name: Obtain and base64 encode .kube/config for cluster
      id: encode_kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ inputs.cluster-name }} --region "${{ inputs.region }}" --kubeconfig eks-config
        b64kubeconfig=$(cat eks-config | base64 -w 0)
        echo "b64kubeconfig=${b64kubeconfig}" >> $GITHUB_OUTPUT