name: "aws-iam-roles-dispatch"

on:
  workflow_dispatch:
    inputs:
      cluster-name:
        description: "Name of the EKS cluster."
        type: string
        required: true
      region:
        description: "The AWS region where the EKS cluster will be created"
        required: true
        type: choice
        options:
        - us-east-1
        - us-east-2
        - us-west-2
        - af-south-1
        - ap-east-1
        - ap-south-1
        - ap-northeast-1
        - ap-northeast-2
        - ap-northeast-3
        - ap-southeast-1
        - ap-southeast-2
        - ca-central-1
        - eu-west-1
        - eu-west-2
        - eu-west-3
        - eu-north-1
        - eu-south-1
        - me-south-1
        - sa-east-1
        default: "us-west-2"
      action:
        required: true
        type: choice
        description: "Create (new) or delete (existing)"
        options:
        - create
        - delete

jobs:
  manage-iam-roles:
    uses: ./.github/workflows/aws-ima-roles.yml
    with:
      cluster-name: ${{ github.event.inputs.cluster-name }}
      region: ${{ github.event.inputs.region }}
      action: ${{ github.event.inputs.action }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      CSP_API_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
