name: "azure-04-dispatch-main-dns-zone"

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "New DNS zone name to create (e.g., example.com)"
        required: true
      resourceGroupName:
        description: "The resource group to provision the main DNS zone in"
        required: true
      action:
        required: true
        type: choice
        description: "Create (new) or destroy (existing)"
        options:
        - create
        - destroy

jobs:
  manage-main-dns-zone:
    uses: ./.github/workflows/azure-main-dns.yml
    with:
      domain: ${{ github.event.inputs.domain }}
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      action: ${{ github.event.inputs.action }}
    secrets:
      AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_BACKEND_resource_group_name: ${{ secrets.TF_BACKEND_resource_group_name }}
      TF_BACKEND_storage_account_name: ${{ secrets.TF_BACKEND_storage_account_name }}
      TF_BACKEND_storage_container_name:  ${{ secrets.TF_BACKEND_storage_container_name }}