name: Delete Deployments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "An existing deployment environment name"
        required: true

jobs:
  delete:
    runs-on: ubuntu-20.04
    steps:
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.PA_TOKEN }}
          environment: ${{ github.event.inputs.environment }}
          onlyRemoveDeployments: true