name: "google-dispatch-autopilot-kubernetes-engine"

on:
  workflow_dispatch:
    inputs:
      cluster-name:
        description: "Name of the GKE cluster"
        required: true
        default: "tap"
      region:
        description: "The Google Cloud region where the GKE cluster will be available"
        required: true
        type: choice
        options:
        - asia-east1
        - asia-east2
        - asia-northeast1
        - asia-northeast2
        - asia-northeast3
        - asia-south1
        - asia-south2
        - asia-southeast1
        - asia-southeast2
        - australia-southeast1
        - australia-southeast2
        - europe-central2
        - europe-north1
        - europe-southwest1
        - europe-west1
        - europe-west2
        - europe-west3
        - europe-west4
        - europe-west6
        - europe-west8
        - europe-west9
        - northamerica-northeast1
        - northamerica-northeast2
        - southamerica-east1
        - southamerica-west1
        - us-central1
        - us-east1
        - us-east4
        - us-east5
        - us-south1
        - us-west1
        - us-west2
        - us-west3
        - us-west4
        default: "us-west2"
      k8s-version:
        description: "A supported and available Kubernetes (major.minor) version"
        required: true
        type: choice
        options:
        - "1.22"
        - "1.23"
        - "1.24"
        - "1.25"
        - "1.26"
        default: "1.24"
      vpc-network-name:
        description: "Name of an existing Google Cloud VPC network"
        required: true
        default: "tap-demo-network"
      action:
        required: true
        type: choice
        description: "Create (new) or destroy (existing)"
        options:
        - create
        - destroy

jobs:
  manage-gke:
    uses: ./.github/workflows/google-k8s-autopilot-cluster.yml
    with:
      cluster-name: ${{ github.event.inputs.cluster-name }}
      region: ${{ github.event.inputs.region }}
      k8s-version: ${{ github.event.inputs.k8s-version }}
      vpc-network-name: ${{ github.event.inputs.vpc-network-name }}
      action: ${{ github.event.inputs.action }}
    secrets:
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      TF_BACKEND_GCS_BUCKET_NAME: ${{ secrets.TF_BACKEND_GCS_BUCKET_NAME }}
      GOOGLE_KMS_KEYRING: ${{ secrets.GOOGLE_KMS_KEYRING }}
      TANZU_NETWORK_API_TOKEN: ${{ secrets.TANZU_NETWORK_API_TOKEN }}
      TANZU_NETWORK_USERNAME: ${{ secrets.TANZU_NETWORK_USERNAME }}
      TANZU_NETWORK_PASSWORD: ${{ secrets.TANZU_NETWORK_PASSWORD }}
      CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
      PA_TOKEN: ${{ secrets.PA_TOKEN }}