name: "google-harbor-dispatch"

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "A domain that the installation of Harbor will be addressable from"
        required: true
      email-address:
        description: "An email address to be used as the owner for the public trusted domain certificate vended by Let's Encrypt"
        required: true
      kubeconfig-contents:
        description: "The base64 encoded contents of a .kube/config file that already has the current Kubernetes cluster context set"
        required: true
      action:
        required: true
        type: choice
        description: "Create (new) or destroy (existing)"
        options:
        - create
        - destroy

jobs:
  harbor-on-google:
    uses: ./.github/workflows/lcm-harbor.yml
    with:
      domain: ${{ github.event.inputs.domain }}
      email-address: ${{ github.event.inputs.email-address }}
      action: ${{ github.event.inputs.action }}
    secrets:
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      KUBECONFIG_CONTENTS: ${{ github.event.inputs.kubeconfig-contents }}
      PA_TOKEN: ${{ secrets.PA_TOKEN }}
