name: "google-dispatch-virtual-private-cloud"

on:
  workflow_dispatch:
    inputs:
      vpc-network-name:
        description: "The Google Cloud VPC network name"
        required: true
        default: "tap-demo-network"
      region:
        description: "The Google Cloud region where the VPC subnetwork will be created"
        required: true
        type: choice
        options:
        - asia-east1
        - asia-east2
        - asia-northeast1
        - asia-northeast2
        - asia-northeast3
        - asia-south1
        - asia-south2
        - asia-southeast1
        - asia-southeast2
        - australia-southeast1
        - australia-southeast2
        - europe-central2
        - europe-north1
        - europe-southwest1
        - europe-west1
        - europe-west2
        - europe-west3
        - europe-west4
        - europe-west6
        - europe-west8
        - europe-west9
        - northamerica-northeast1
        - northamerica-northeast2
        - southamerica-east1
        - southamerica-west1
        - us-central1
        - us-east1
        - us-east4
        - us-east5
        - us-south1
        - us-west1
        - us-west2
        - us-west3
        - us-west4
        default: "us-west2"
      action:
        required: true
        type: choice
        description: "Create (new) or destroy (existing)"
        options:
        - create
        - destroy

jobs:
  manage-vpc:
    uses: ./.github/workflows/google-virtual-network.yml
    with:
      vpc-network-name: ${{ github.event.inputs.vpc-network-name }}
      region: ${{ github.event.inputs.region }}
      action: ${{ github.event.inputs.action }}
    secrets:
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      TF_BACKEND_GCS_BUCKET_NAME: ${{ secrets.TF_BACKEND_GCS_BUCKET_NAME }}
      GOOGLE_KMS_KEYRING: ${{ secrets.GOOGLE_KMS_KEYRING }}