name: "google-dispatch-remote-backend-for-terraform-state"

on:
  workflow_dispatch:
    inputs:
      google-project-id:
        description: "Google project that is hosting the Cloud Storage bucket for all Terraform module state management"
        required: true
      google-service-account-key:
        description: "Base64-encoded service account keyfile contents of an account with create/encrypt/decrypt permissions to a Cloud KMS keyring"
        required: true
      bucket-name:
        description: "Google Cloud storage bucket name used for Terraform state. (This value will be suffixed. On destroy, be sure to use suffixed name)."
        required: true
        type: string
        default: "tap"
      region:
        description: "The Google Cloud region where the bucket will be created to manage Terraform state"
        required: true
        type: choice
        options:
        - asia-east1
        - asia-east2
        - asia-northeast1
        - asia-northeast2
        - asia-northeast3
        - asia-south1
        - asia-south2
        - asia-southeast1
        - asia-southeast2
        - australia-southeast1
        - australia-southeast2
        - europe-central2
        - europe-north1
        - europe-southwest1
        - europe-west1
        - europe-west2
        - europe-west3
        - europe-west4
        - europe-west6
        - europe-west8
        - europe-west9
        - northamerica-northeast1
        - northamerica-northeast2
        - southamerica-east1
        - southamerica-west1
        - us-central1
        - us-east1
        - us-east4
        - us-east5
        - us-south1
        - us-west1
        - us-west2
        - us-west3
        - us-west4
        default: "us-west2"
      action:
        required: true
        type: choice
        description: "Create (new) or destroy (existing)"
        options:
        - create
        - destroy

jobs:
  manage-backend-storage:
    uses: ./.github/workflows/google-provided-remote-backend.yml
    with:
      bucket-name: ${{ github.event.inputs.bucket-name }}
      region: ${{ github.event.inputs.region }}
      action: ${{ github.event.inputs.action }}
    secrets:
      GOOGLE_PROJECT_ID: ${{ github.event.inputs.google-project-id }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ github.event.inputs.google-service-account-key }}
      PA_TOKEN: ${{ secrets.PA_TOKEN }}
      GOOGLE_KMS_KEYRING: ${{ secrets.GOOGLE_KMS_KEYRING }}
