name: "install-tanzu-data-services-repo-dispatch"

on:
  workflow_dispatch:
    inputs:
      tds-version:
        description: "Tanzu Data Services Package Repository version"
        type: string
        required: true
        default: "1.8.0"
      cluster-provider:
        description: "The Kubernetes service provider"
        required: true
        type: choice
        options:
          - eks
          - aks
          - gke
          - tkg»aws
          - tkg»azure
      kubeconfig-contents:
        description: "The base64 encoded contents of a .kube/config file that already has the current Kubernetes cluster context set"
        required: true

jobs:
  install-tanzu-data-services-rep-on-azure:
    if: contains(fromJson('["aks","tkg»azure"]'), github.event.inputs.cluster-provider)
    uses: ./.github/workflows/install-tanzu-data-services-repo.yml
    with:
      tds-version: ${{ github.event.inputs.tds-version }}
      cluster-provider: ${{ github.event.inputs.cluster-provider }}
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      TANZU_NETWORK_API_TOKEN: ${{ secrets.TANZU_NETWORK_API_TOKEN }}
      TANZU_NETWORK_USERNAME: ${{ secrets.TANZU_NETWORK_USERNAME }}
      TANZU_NETWORK_PASSWORD: ${{ secrets.TANZU_NETWORK_PASSWORD }}
      CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
      PA_TOKEN: ${{ secrets.PA_TOKEN }}
      KUBECONFIG_CONTENTS: ${{ github.event.inputs.kubeconfig-contents }}

  install-tanzu-data-services-repo-on-aws:
    if: contains(fromJson('["eks","tkg»aws"]'), github.event.inputs.cluster-provider)
    uses: ./.github/workflows/install-tanzu-data-services-repo.yml
    with:
      tds-version: ${{ github.event.inputs.tds-version }}
      cluster-provider: ${{ github.event.inputs.cluster-provider }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TANZU_NETWORK_API_TOKEN: ${{ secrets.TANZU_NETWORK_API_TOKEN }}
      TANZU_NETWORK_USERNAME: ${{ secrets.TANZU_NETWORK_USERNAME }}
      TANZU_NETWORK_PASSWORD: ${{ secrets.TANZU_NETWORK_PASSWORD }}
      CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
      PA_TOKEN: ${{ secrets.PA_TOKEN }}
      KUBECONFIG_CONTENTS: ${{ github.event.inputs.kubeconfig-contents }}

  install-tanzu-data-services-repo-on-google:
    if: github.event.inputs.cluster-provider == 'gke'
    uses: ./.github/workflows/install-tanzu-data-services-repo.yml
    with:
      tds-version: ${{ github.event.inputs.tds-version }}
      cluster-provider: ${{ github.event.inputs.cluster-provider }}
    secrets:
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      TANZU_NETWORK_API_TOKEN: ${{ secrets.TANZU_NETWORK_API_TOKEN }}
      TANZU_NETWORK_USERNAME: ${{ secrets.TANZU_NETWORK_USERNAME }}
      TANZU_NETWORK_PASSWORD: ${{ secrets.TANZU_NETWORK_PASSWORD }}
      CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
      PA_TOKEN: ${{ secrets.PA_TOKEN }}
      KUBECONFIG_CONTENTS: ${{ github.event.inputs.kubeconfig-contents }}