name: "uninstall-tanzu-standard-repo-dispatch"

on:
  workflow_dispatch:
    inputs:
      cluster-provider:
        description: "The Kubernetes service provider"
        required: true
        type: choice
        options:
          - eks
          - aks
          - gke
          - tkg»aws
          - tkg»azure
          - other
      kubeconfig-contents:
        description: "The base64 encoded contents of a .kube/config file that already has the current Kubernetes cluster context set"
        required: true

jobs:
  uninstall-tanzu-standard-repo:
    if: contains(fromJson('["aks","gke","other"]'), inputs.cluster-provider)
    uses: ./.github/workflows/uninstall-tanzu-standard-repo.yml
    with:
      cluster-provider: ${{ github.event.inputs.cluster-provider }}
    secrets:
      KUBECONFIG_CONTENTS: ${{ github.event.inputs.kubeconfig-contents }}
      CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}

  uninstall-tanzu-standard-repo-on-eks:
    if: github.event.inputs.cluster-provider == 'eks'
    uses: ./.github/workflows/uninstall-tanzu-standard-repo.yml
    with:
      cluster-provider: ${{ github.event.inputs.cluster-provider }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      KUBECONFIG_CONTENTS: ${{ github.event.inputs.kubeconfig-contents }}
      CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}

  uninstall-tanzu-standard-repo-on-gke:
    if: github.event.inputs.cluster-provider == 'gke'
    uses: ./.github/workflows/uninstall-tanzu-standard-repo.yml
    with:
      cluster-provider: ${{ github.event.inputs.cluster-provider }}
    secrets:
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
      GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      KUBECONFIG_CONTENTS: ${{ github.event.inputs.kubeconfig-contents }}
      CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
