#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tds:
  credentials:
    tanzuNet:
      host: registry.tanzu.vmware.com
      username: TANZUNET_USERNAME
      password: TANZUNET_PASSWORD
